format = "$directory$git_branch$git_status"
add_newline = false

[git_branch]
symbol = "ğŸŒ± "
style = "bold blue"

[git_status]
style = "blue"
conflicted = "ğŸš©"
ahead = "â©${count}"
behind = "âª${count}"
diverged = "ğŸ¤· â¬†ï¸a${ahead_count} â¬‡ï¸${behind_count}"
up_to_date = "âœ…"
untracked = "â“"
modified = "âœï¸"
stashed = "ğŸ“¦"
staged = '[++\($count\)](green)'
deleted = "ğŸ—‘ï¸"
